# -*- coding: utf-8 -*-
"""AI-Verse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6MqgBfH1CESLVqnBcreVEojmABJLoeK
"""

!pip install -q gradio transformers torch gTTS accelerate bitsandbytes

# EchoVerse - AI-Powered Audiobook Creation Tool
# Single-cell Google Colab implementation with Gradio UI

# Step 1: Install required packages
print("📦 Installing required packages...")
!pip install -q gradio transformers torch gTTS accelerate bitsandbytes

# Step 2: Import libraries
print("📚 Importing libraries...")
import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from gtts import gTTS
import os
from datetime import datetime

# Step 3: Initialize IBM Granite model
print("🧠 Loading IBM Granite 3.0 2B Instruct model...")
model_name = "ibm-granite/granite-3.0-2b-instruct"

# Load tokenizer and model with optimizations for Colab
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True
)

print("✅ Model loaded successfully!")

# Step 4: Define tone rewriting function
def rewrite_text_with_tone(text, tone):
    """Rewrites text in the specified tone using IBM Granite model"""

    tone_prompts = {
        "Neutral": "Rewrite the following text in a clear, neutral, and objective tone. Maintain all key information but use balanced, factual language:",
        "Suspenseful": "Rewrite the following text in a suspenseful, mysterious, and tension-building tone. Add dramatic elements while keeping the core meaning:",
        "Inspiring": "Rewrite the following text in an inspiring, uplifting, and motivational tone. Make it emotionally powerful and encouraging:"
    }

    prompt = f"""{tone_prompts[tone]}

Original Text: {text}

Rewritten Text:"""

    # Tokenize and generate
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=512,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    # Decode output
    full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract only the rewritten portion
    rewritten = full_response.split("Rewritten Text:")[-1].strip()

    return rewritten

# Step 5: Define text-to-speech function
def text_to_speech(text, voice):
    """Converts text to speech using gTTS with voice selection"""

    # Map voice names to language/accent codes
    voice_map = {
        "Lisa (US Female)": ("en", "us"),
        "Michael (US Male)": ("en", "us"),
        "Allison (UK Female)": ("en", "co.uk")
    }

    lang, tld = voice_map[voice]

    # Generate speech
    tts = gTTS(text=text, lang=lang, tld=tld, slow=False)

    # Save to file with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    audio_file = f"echoverse_audio_{timestamp}.mp3"
    tts.save(audio_file)

    return audio_file

# Step 6: Main processing function
def create_audiobook(original_text, tone, voice):
    """Main function that processes text and creates audiobook"""

    if not original_text or not original_text.strip():
        return None, "⚠️ Please enter some text to process", original_text

    try:
        # Step 1: Rewrite text with selected tone
        status_msg = f"🔄 Rewriting text in {tone} tone..."
        print(status_msg)

        rewritten_text = rewrite_text_with_tone(original_text, tone)

        # Step 2: Convert to speech
        status_msg = f"🎙️ Converting to speech with {voice}..."
        print(status_msg)

        audio_file = text_to_speech(rewritten_text, voice)

        # Step 3: Create comparison display
        comparison = f"""
### 📝 Original Text:
{original_text}

---

### ✨ {tone} Version:
{rewritten_text}
"""

        success_msg = f"✅ Audiobook created successfully! Tone: {tone} | Voice: {voice}"

        return audio_file, comparison, success_msg

    except Exception as e:
        error_msg = f"❌ Error: {str(e)}"
        return None, error_msg, original_text

# Step 7: Create Gradio Interface
def create_interface():
    """Creates the Gradio UI for EchoVerse"""

    with gr.Blocks(title="EchoVerse - AI Audiobook Creator", theme=gr.themes.Soft()) as app:

        gr.Markdown("""
        # 🎧 EchoVerse - AI-Powered Audiobook Creation Tool
        Transform your text into expressive, downloadable audio content with AI-powered tone adaptation
        """)

        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("### 📝 Input Settings")

                # Text input
                input_text = gr.Textbox(
                    label="Enter Your Text",
                    placeholder="Type or paste the text you want to convert to an audiobook...",
                    lines=8,
                    max_lines=15
                )

                # Tone selection
                tone_dropdown = gr.Dropdown(
                    choices=["Neutral", "Suspenseful", "Inspiring"],
                    value="Neutral",
                    label="Select Tone Style",
                    info="Choose how you want the text to be rewritten"
                )

                # Voice selection
                voice_dropdown = gr.Dropdown(
                    choices=["Lisa (US Female)", "Michael (US Male)", "Allison (UK Female)"],
                    value="Lisa (US Female)",
                    label="Select Voice",
                    info="Choose the narrator's voice"
                )

                # Generate button
                generate_btn = gr.Button("🎬 Create Audiobook", variant="primary", size="lg")

                # Status message
                status_output = gr.Textbox(label="Status", interactive=False, lines=2)

            with gr.Column(scale=1):
                gr.Markdown("### 🎵 Output")

                # Audio player
                audio_output = gr.Audio(
                    label="Generated Audiobook",
                    type="filepath",
                    interactive=False
                )

                # Text comparison
                comparison_output = gr.Markdown(label="Text Comparison")

        # Info section
        gr.Markdown("""
        ---
        ### 📖 Features:
        - **Tone-Adaptive Rewriting**: Transforms text using IBM Granite 3.0 2B Instruct AI
        - **High-Quality Narration**: Natural-sounding voice synthesis
        - **Downloadable Audio**: Save your audiobook as MP3
        - **Side-by-Side Comparison**: See original and adapted text together
        - **Multiple Voices & Tones**: Customize your audiobook experience

        ### 💡 Tips:
        - For best results, use clear and well-structured text (50-500 words)
        - Experiment with different tone-voice combinations
        - Download your audio file before generating a new one
        """)

        # Connect function to button
        generate_btn.click(
            fn=create_audiobook,
            inputs=[input_text, tone_dropdown, voice_dropdown],
            outputs=[audio_output, comparison_output, status_output]
        )

    return app

# Step 8: Launch the app
print("\n🚀 Launching EchoVerse...")
print("=" * 60)

app = create_interface()
app.launch(
    share=True,
    debug=True,
    show_error=True
)

print("\n✅ EchoVerse is now running!")
print("📱 Use the public URL to access from any device")
print("=" * 60)